apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: chat-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/chatapp"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_CLIENT_ID
          value: "chat-app"
        - name: KAFKA_GROUP_ID
          value: "chat-group"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: chat-app
spec:
  selector:
    app: chat-backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP