apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: chat-frontend
        image: 1911997/chat-frontend:v1.0
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: chat-app
spec:
  selector:
    app: chat-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer